### ISSUE TITLE
能不能把英文翻译成中文

### ISSUE THREAD

**Issue by talentsun** [limijiaoyin/bvod-portal#238]
![image](https://cloud.githubusercontent.com/assets/1879787/5153421/25b71ff2-7263-11e4-964c-4468c71a9f7e.png)

**Comment by JilinXie** [comment]
Converted the "live stream" to chinese, this can be done by adding 'title' configuration. But this setting would also affect the startup button

Well, this seems more complex to solve, since feedbacks from jwplayer support describe no existing build-in function solving this. But there should be a way to modify source code to get whatever we prefer.

However, we simply just use the title config,,, in auto-start mode, this problem will not be seen by users.
